version: '3.1'

services:
  app:
    container_name: docker-leechcode
    restart: always
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB} 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081