version: '3.1'

services:
  app:
    container_name: docker-leechcode
    restart: always
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081